version: '3.7'

services:
  massive:
    container_name: massive
    image: wiezmankimchi/massive-react
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    network_mode: front
